# Generated by Django 3.1.2 on 2021-02-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210217_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescope',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='articles',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleScope',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
