# Generated by Django 3.1.2 on 2021-02-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210217_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.ArticleScope', to='articles.Scope'),
        ),
        migrations.AddField(
            model_name='scope',
            name='articles',
            field=models.ManyToManyField(through='articles.ArticleScope', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(verbose_name='Главная рубрика'),
        ),
        migrations.AlterUniqueTogether(
            name='articlescope',
            unique_together={('article', 'scope')},
        ),
    ]
