# Generated by Django 3.1.2 on 2021-02-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210217_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.RenameField(
            model_name='articlescope',
            old_name='scope',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(verbose_name='Главный тэг'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='articles',
            field=models.ManyToManyField(related_name='scopes', through='articles.ArticleScope', to='articles.Article'),
        ),
        migrations.AlterUniqueTogether(
            name='articlescope',
            unique_together=set(),
        ),
    ]
